---
title: 'Class04: Intro to API'
author: "Paige Charlton"
date: "2026-02-11"
output: 
  html_document:
  toc: TRUE
  toc_float: TRUE
  number_section: TRUE
  code_downlaod: TRUE
  code_folding: SHOW
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Getting Data from the USAJobs API

```{r}
# var request = require('request');    
#             
# var host = 'data.usajobs.gov';  
# var userAgent = 'your@email.address';  
# var authKey = 'YourAPIKey';    
#             
# request({      
#     url: 'https://data.usajobs.gov/api/search?JobCategoryCode=2210&Keyword=Software Development&LocationName=Washington, DC',      
#     method: 'GET',      
#     headers: {          
#         "Host": host,          
#         "User-Agent": userAgent,          
#         "Authorization-Key": authKey      
#     }  
# }, function(error, response, body) {      
#     var data = JSON.parse(body);  
# });

host = 'data.usajobs.gov'
user_agent = 'charltpr@miamioh.edu'
auth_key =  "mPMPJefGooYCE4Jc7Y2Xqhlt6/tIokbnNYxWl8zWj70="

my_req = httr2::request("https://data.usajobs.gov/api/search") |> 
  httr2::req_headers(
    Host = host,          
   `User-Agent` = user_agent,          
    `Authorization-Key` = auth_key
  ) |> 
  httr2::req_url_query(
   # JobCategoryCode=2210&Keyword=Software Development
    JobCategoryCode = 2210,
    Keyword = "Data Analyst",
    ResultsPerPage=500
  )

response = httr2::req_perform(my_req)

usajobs_data = response |>
  httr2::resp_body_string() |>
  jsonlite::fromJSON(flatten = T)

# dplyr::glimpse(usajobs_data)

usajobs_df = usajobs_data$SearchResult$SearchResultItems

usajobs_df |>
  tidyr::unnest(
    cols = c(
    "MatchedObjectDescriptor.PositionLocation",
    "MatchedObjectDescriptor.JobCategory",
    "MatchedObjectDescriptor.PositionSchedule"
    ),
    names_sep= '.'
  ) -> 
  usajobs_df_clean

usajobs_df_clean |>
dplyr::distinct(MatchedObjectId, MatchedObjectDescriptor.OrganizationName) |> 
  dplyr::count(
    MatchedObjectDescriptor.OrganizationName
  )
```