---
title: "Class05WebScraping"
author: "Paige Charlton"
date: "2026-02-16"
output: 
  html_document:
    toc: TRUE
    toc_float: TRUE
    number_sections: TRUE
    code_download: TRUE
    code_folding: show
    
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r bls}
robotstxt::paths_allowed(
  paths  = "/ooh/", domain = "www.bls.gov", bot    = "*"
)
```

```{r indeed}
robotstxt::paths_allowed(
  paths  = "/jobs/", domain = "www.indeed.com"
)
```
Given that the return is true it means that we are allowed to scrape this webpage (directory from the website)

```{r linkedin}
robotstxt::paths_allowed(
  paths  = "/jobs/", domain = "www.linkedin.com"
)
```

# The BLS Scrape Example 

```{r}
robotstxt::paths_allowed(
  paths = "/emp/",
  domain = "https://www.bls.gov/"
)


resp = httr2::request(
  "https://www.bls.gov/emp/tables/fastest-growing-occupations.htm"
) |>
  httr2::req_user_agent("An ISA 401 Bot from Miami University") |>
  httr2::req_perform()
  

bls_webpage = resp |> httr2::resp_body_raw() |> rvest::read_html()
bls_webpage


#step 2 which is to utilize CSS selectors to just focus on the table 
bls_webpage |>
  rvest::html_elements(css = "#BLStable_2025_7_18_12_5") -> 
  bls_table_element 

# step 3: extract the table / clean it (make it human readable)
bls_table_element |> rvest::html_table() -> bls_table

bls_table_clean = bls_table[[1]]


# DISCLAIMER: You might hate that there are no single right ways for the 
# SELECTOR
bls_webpage |>
  rvest::html_elements("table") |>
  rvest::html_table() |> 
  magrittr::extract2(1) -> #extract 2 is equivalent to my [[]]; 1 is first sublist
  tbl_b

bls_webpage |>
  rvest::html_elements(".regular") |>
  rvest::html_table() |> 
  magrittr::extract2(1) -> #extract 2 is equivalent to my [[]]; 1 is first sublist
  tbl_c

bls_webpage |>
  rvest::html_elements("div > table") |>
  rvest::html_table() |> 
  magrittr::extract2(1) -> #extract 2 is equivalent to my [[]]; 1 is first sublist
  tbl_d
```
